#!/bin/bash
# This file must be in the exec= line of /usr/share/xsessions/xmonad.desktop

# Launch trayer - system tray app
trayer --edge top --align right --SetDockType true --SetPartialStrut false --expand true --width 10 --transparent false --height 18 &

# Launch sound controls
gnome-sound-applet &

# Launch network controls
# nm-applet & # networkmanager from GNOME
wicd-client -t & # wicd startup

# Start f-lux/redshift to control coloring
redshift -t 6200:3500 &

# Runs emacs daemon... emacsclient -c or emacsclient -t to connect
# emacs --daemon

# Start dropbox
dropbox start

# Unclutter to hide mouse on inactivity
unclutter &

# Turn off keyboard backlight
echo 0 | sudo tee -a /sys/class/leds/smc::kbd_backlight/brightness

# Turn off annoying headphone light on macbook
amixer set IEC958 off

# Caps becomes ctrl
setxkbmap -option ctrl:nocaps

# Touchpad settings
synclient MaxTapTime=0 # disable tap-to-click (180 default)
synclient HorizTwoFingerScroll=1 # enable side-scrolling (0 default)
synclient PalmDetect=1 # enable palm detection (0 default)

# Set wallpaper
feh --bg-scale ~/Documents/ch.jpg

exec xmonad
